/* What is the most and least revenue we have generated by an order */
SELECT MAX(order_revenue) AS max_revenue, MIN(Order_revenue) AS min_revenue
FROM (
  SELECT Order_id, SUM(Revenue) AS order_revenue
  FROM SALES
  GROUP BY Order_id)
AS order_totals;
